version: '3'

services:
  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  # Backend service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/iss_cargo_db
      - NODE_ENV=production

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=iss_cargo_db

volumes:
  mongodb_data:
